// Load env Variables----------------------------------------------------
import Anthropic from "@anthropic-ai/sdk";
import * as dotenv from "dotenv";

dotenv.config();


const client = new Anthropic();
const model = "claude-haiku-4-5";


// Helper Functions
const addUserMessage = (messages: Anthropic.MessageParam[], text: string) => {
    messages.push({ role: "user", content: text });
};

const userPrompt = "Generate a one sentence description of a Nextjs app";
const messages: Anthropic.MessageParam[] = [];
addUserMessage(messages, userPrompt);

//================================================================================================================================
// DO NOT COMMENT OUT THE ABOVE CODE
//================================================================================================================================




//================================================
// Response Streaming
    // lets users see text appear chunk by chunk
    // as Claude generates it, creating a much
    // more responsive feel

// In a typical chat setup, your server sends
// a user message to Claude and waits for
// the complete response before sending
// anything back to the client

// With streaming enabled, Claude immediately sends
// back an initial response indicating it has
// received your request and is starting to
// generate text. Then you receive a series of
// events, each containing a small piece of the
// overall response

// Your server can forward these text chunks to
// your client application as they arrive,
// allowing users to see the response building up
// word by word. All of these events are part of
// a single request to Claude.
//================================================

// const streamChatRaw = async (messages: Anthropic.MessageParam[]) => {
//     const stream = await client.messages.create({
//         model,
//         max_tokens: 1000,
//         messages,
//         stream: true,   // To enable streaming, add stream: true to your messages.create call
//     });

//     for await (const event of stream) {
//         console.log(event);
//     }
// };

// await streamChatRaw(messages);



// When you enable streaming, Claude sends back several types of events:
    // message_start       : A new message is being sent
    // content_block_start : Start of a new block containing text, tool use, or other content
    // content_block_delta : Chunks of the actual generated text
    // content_block_stop  : The current content block has been completed
    // message_delta       : The current message is complete
    // message_stop        : End of information about the current message


// content_block_delta
    // This event contains the actual text that is being generated by Claude
    // and sent back chunk by chunk, that you'll want to display to users


//=========================================================================================================================================
// COMMENT OUT CODE ABOVE TO RUN BELOW CODE
//=========================================================================================================================================
// Once the streaming events are returned we would
// need to extract the text from them then send
// the text back down


// You could manually parse events, or you can
// use the SDK's simplified streaming interface
// that extracts just the text content


//================================================
// Manual Event Parsing
//   Instead of printing every event, we check
//   each event's type and pull out only the
//   text chunks from content_block_delta events
//================================================
//*******************************************************************************************************************
// const streamChatManual = async (messages: Anthropic.MessageParam[]) => {
//     const stream = await client.messages.create({
//         model,
//         max_tokens: 1000,
//         messages,
//         stream: true,
//     });

//     let fullResponse = "";

//     for await (const event of stream) {
//         // content_block_delta is the only event that carries actual text chunks
//             // Filters out all the start/stop bookkeeping events,
//             // keeping only the ones that carry actual content
//         if (event.type === "content_block_delta") {
//             // delta.type === "text_delta" confirms this chunk contains text (not a tool call)
//                 // Filters out tool call chunks (which are also deltas but contain JSON, not text)
//             if (event.delta.type === "text_delta") {
//                 const chunk = event.delta.text;
//                 fullResponse += chunk;

//                 // process.stdout.write keeps chunks on the same line without adding a newline
//                 // In Node.js there is no flush needed - stdout writes are immediate
//                 process.stdout.write(chunk);
//             }
//         }
//     }

//     console.log(); // newline after streaming finishes

//     // fullResponse accumulator is the part you would send back to a client in a real server
//     // Each chunk goes out immediately via streaming, but you also build the complete string
//     // so you can store it in your message history afterward
//     return fullResponse;
// };

// const messages2: Anthropic.MessageParam[] = [];
// addUserMessage(messages2, userPrompt);
// await streamChatManual(messages2);
//*******************************************************************************************************************


//=========================================================================================================================================
// COMMENT OUT CODE ABOVE TO RUN THE CODE BELOW
//=========================================================================================================================================


//==========================================================================================================================================================================
// SDK Simplified Streaming Interface
//   client.messages.stream() handles all event
//   parsing for you. No type checks needed.
//==========================================================================================================================================================================

//*******************************************************************************************************************
//======================SDK Simplified Streaming Interface==========================================================
// This approach automatically filters out everything
// except the actual text content, which is usually
// what you need for displaying responses to users


const main = async () => {
    const messages3: Anthropic.MessageParam[] = [];
    addUserMessage(messages3, userPrompt);

    // .stream() is a context manager equivalent in TypeScript - handles connection cleanup
    const stream = client.messages.stream({
        model,
        max_tokens: 1000,
        messages: messages3,
    });

    // .textStream is an async iterable that yields only text chunks
    // the SDK handles all the event filtering internally
    for await (const chunk of stream.textStream) {
        process.stdout.write(chunk);
    }

    console.log(); // newline after streaming finishes

    // .finalMessage() returns the complete response object
    // same shape as a non-streaming client.messages.create() response
    const final = await stream.finalMessage();
    return (final.content[0] as Anthropic.TextBlock).text;
};

main();
