from dotenv import load_dotenv
from anthropic import Anthropic


load_dotenv()


client = Anthropic()
model = "claude-haiku-4-5"


# Helper Functions
def add_user_message(messages, text):
    user_message = {"role": "user", "content": text}
    messages.append(user_message)

def add_assistant_message(messages, text):
    assistant_message = {"role": "assistant", "content": text}
    messages.append(assistant_message)

user_prompt = "Generate a one sentence description of a Nextjs app"
messages = []
add_user_message(messages, user_prompt)

#================================================================================================================================
# DO NOT COMMENT OUT THE ABOVE CODE
#================================================================================================================================




#================================================
# Response Streaming
    # lets users see text appear chunk by chunk 
    # as Claude generates it, creating a much 
    # more responsive feel

# In a typical chat setup, your server sends 
# a user message to Claude and waits for 
# the complete response before sending 
# anything back to the client

# With streaming enabled, Claude immediately sends
# back an initial response indicating it has 
# received your request and is starting to 
# generate text. Then you receive a series of 
# events, each containing a small piece of the 
# overall response

# Your server can forward these text chunks to 
# your client application as they arrive, 
# allowing users to see the response building up 
# word by word. All of these events are part of 
# a single request to Claude.
#================================================

# def stream_chat(messages):
#     params = {
#         "model": model,
#         "max_tokens": 1000,
#         "messages": messages,
#         "stream":True # To enable streaming, add stream=True to your messages.create call
#     }

#     stream = client.messages.create(**params)
    
#     for event in stream:
#         print(event)



# messages = []

# add_user_message(messages, user_prompt)

# stream_chat(messages)



# When you enable streaming, Claude sends back several types of events:
    # RawMessageStartEvent : A new message is being sent
    # RawContentBlockStartEvent : Start of a new block containing text, tool use, or other content
    # RawContentBlockDeltaEvent : Chunks of the actual generated text
    # RawContentBlockDeltaEvent : Chunks of the actual generated text
    # RawContentBlockStopEvent : The current content block has been completed
    # RawMessageDeltaEvent : The current message is complete
    # RawMessageStopEvent : End of information about the current message


# RawContentBlockDeltaEvent
    # This event contains the actual text that is being generated by Claude
    # and sent back chunk by chunk, that you'll want to display to users


#=========================================================================================================================================
# COMMENT OUT CODE ABOVE TO RUN BELOW CODE
#=========================================================================================================================================
# Once the streaming events are returned we would 
# need to extract the text from them then send 
# the text back down


# You could manually parsing events, or you can 
# use the SDK's simplified streaming interface 
# that extracts just the text content


#================================================
# Manual Event Parsing
#   Instead of printing every event, we check
#   each event's type and pull out only the
#   text chunks from RawContentBlockDeltaEvent
#================================================
#******************************************************************************************************************
# def stream_chat_manual(messages):
#     params = {
#         "model": model,
#         "max_tokens": 1000,
#         "messages": messages,
#         "stream": True
#     }

#     stream = client.messages.create(**params)

#     full_response = ""

#     for event in stream:
#         # RawContentBlockDeltaEvent is the only event that carries actual text chunks
#             # Filters out all the start/stop bookkeeping events, 
#             # keeping only the ones that carry actual content
#         if event.type == "content_block_delta":
#             # delta.type == "text_delta" confirms this chunk contains text (not a tool call)
#                 # Filters out tool call chunks (which are also deltas but contain JSON, not text)
#             if event.delta.type == "text_delta":
#                 chunk = event.delta.text
#                 full_response += chunk

#                 # end="" and flush=True on the print
#                 # By default print() adds a newline and buffers output 
#                     # end="" keeps chunks on the same line as they stream in
#                     # flush=True forces Python to write each chunk to the 
#                     # terminal immediately instead of waiting to batch them
#                     # Without flush=True, you would see the whole response 
#                     # appear at once at the end, defeating the purpose of streaming
#                 print(chunk, end="", flush=True)  # print each chunk as it arrives

#     print()  # newline after streaming finishes

#     # full_response accumulator is the part you would send back to a client in a real server 
#     # Each chunk goes out immediately via streaming, but you also build the complete string 
#     # so you can store it in your message history afterward
#     return full_response


# messages2 = []
# add_user_message(messages2, user_prompt)
# stream_chat_manual(messages2)
#=========================================================================================================================================
#******************************************************************************************************************




#=========================================================================================================================================
# COMMENT OUT CODE ABOVE TO RUN THE CODE BELOW
#=========================================================================================================================================


#==========================================================================================================================================================================
# SDK Simplified Streaming Interface
#   client.messages.stream() handles all event
#   parsing for you. No type checks needed.
#==========================================================================================================================================================================

#******************************************************************************************************************
#======================SDK Simplified Streaming Interface==========================================================
# This approach automatically filters out everything 
# except the actual text content, which is usually
# what you need for displaying responses to users


add_user_message(messages, user_prompt)

with client.messages.stream(
    model=model,
    max_tokens=1000,
    messages=messages
) as stream:
    for text in stream.text_stream:
        print(text, end="")

#==================================================================================================================
#******************************************************************************************************************

#==================================================================================================================
# COMMENT OUT CODE ABOVE TO RUN THE CODE BELOW
#==================================================================================================================

#******************************************************************************************************************
#===============================SDK Simplified Streaming Interface=================================================
# Getting the Complete Message using stream.get_final_message()
    # While streaming individual chunks is great for user experience,
    # you often need the complete message for storage or further processing
    # After streaming completes, you can get the assembled final message:
with client.messages.stream(
    model=model,
    max_tokens=1000,
    messages=messages
) as stream:
    for text in stream.text_stream:
        # Send each chunk to your client
        pass
    
    # Get the complete message for database storage
    final_message = stream.get_final_message()

# This gives you the best of both worlds: real-time streaming for users 
# and a complete message object for your application logic
#==================================================================================================================
#******************************************************************************************************************

#=================================================================================================================
# COMMENT OUT CODE ABOVE TO RUN THE CODE BELOW
#=================================================================================================================


# #******************************************************************************************************************
# #===============================SDK Simplified Streaming Interface=================================================
# def stream_chat_sdk(messages):
#     # .stream() is a context manager - it opens and closes the connection cleanly
#     with client.messages.stream(
#         model=model,
#         max_tokens=1000,
#         messages=messages,
#     ) as stream:
#         # .text_stream is a generator that yields only the text chunks
#         # the SDK handles all the event filtering internally
#         for chunk in stream.text_stream:
#             print(chunk, end="", flush=True)

#     print()  # newline after streaming finishes

#     # .get_final_message() returns the complete response object
#     # same shape as a non-streaming client.messages.create() response
#     final = stream.get_final_message()
#     return final.content[0].text


# add_user_message(messages, user_prompt)
# stream_chat_sdk(messages)
#******************************************************************************************************************
